#datasource
spring:
  datasource:
    druid:
      name: devdb
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.209:3306/drugstore_regulation_tst?userUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: yaoyi_dev
      password: 'Yaoyi_2018'
      initial-size: 10
      max-active: 20
server:
  port: 8096
management:
  security:
    enabled: false
drugstore:
  loginurl: 'http://218.204.93.165:8092/login'
  apiurl: 'http://218.204.93.165:8093/api'
  initialpassword: '123456'